name: athmovil_checkout_dummy
description: Example app for the ATH Móvil Checkout Flutter plugin.
publish_to: 'none'
version: 6.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  athmovil_checkout_flutter:
    path: ../

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations