name: athmovil_checkout_flutter
description: Flutter plugin for integrating the ATH Móvil Payment Secure Button on Android and iOS.
version: 6.1.0
homepage: https://github.com/evertec/athmovil-flutter-sdk
repository: https://github.com/evertec/athmovil-flutter-sdk
issue_tracker: https://github.com/evertec/athmovil-flutter-sdk/issues
documentation: https://github.com/evertec/athmovil-flutter-sdk#readme


environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.13.0
  uuid: ^4.5.1
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.6

flutter:
  generate: true

  plugin:
    platforms:
      android:
        package: com.evertec.athmovil.athmovil_checkout_flutter
        pluginClass: AthmovilCheckoutFlutterPlugin
      ios:
        pluginClass: AthmovilCheckoutFlutterPlugin

  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/

screenshots:
  - description: ATH Móvil payment flow example
    path: paymentux.png

flutter_intl:
  enabled: true
  class_name: AppLocalizations